### ISSUE TITLE
Getting Error in config.yml

### ISSUE THREAD

**Issue by theboyrossy** [alombarte/raspberry-osmc-automated#1]
Hi, 
I'm getting an error during the move: section of the config.yml as below,
2015-09-26 23:36 ERROR    entry         sort-files      Failed ncis.la.701.hdtv-lol (Path value replacement `/home/osmc/TV Shows/{{ tvdb_series_name }}/Season {{ tvdb_season }}` failed: (UndefinedError) 'tvdb_series_name' is undefined)

I'm not that linux knowledgable, I've been struggling to get things working properly for a few days now.
Thanks for any help your able to provide.

**Comment by alombarte** [comment]
Thanks for reporting.

What is happening here is that the TVDB service (which returns TV Shows information) doesn't know what to do with the filename `ncis.la.701.hdtv-lol`. There is a section inside the `config.yml` that defines  exceptions that do not work. Try to add this serie:

```
 series:
      - Adventure Time
      - NCIS: Los Angeles
```

Maybe passing the series ID helps also (http://thetvdb.com/index.php?tab=series&id=95441&lid=7)

```
 series:
      - Adventure Time
      - NCIS: Los Angeles
        set:
          tvdb_id: 95441
```

In any case, I just commited a fix, so if the series name is not found will rename the file using the word "Unknown" but will keep going. But still, you should handle exceptions manually.

Let me know if that worked for you.

All the best

**Comment by theboyrossy** [comment]
I was able to edit your configure using information based on this forum post, http://discuss.flexget.com/t/match-filename-with-all-numeric-season-episode/805

This gave me the ability to rename these problem files.
