### ISSUE TITLE
Fresh Install - a few bumps

### ISSUE THREAD

**Issue by bernardomaciel** [alombarte/raspberry-osmc-automated#10]
Hi!

I am opening this issue as a follow up on #8 and #9 .
I performed a fresh install on OSMC 2016.10-1 and hit a few bumps.
I am listing them down, hoping they can be corrected or maybe help others.

1. flexget fails to install

As reported in #8 , there are problems when installing flexget.
I followed the suggestions there and did:

```
sudo apt-get remove python-pip
sudo easy_install -U pip
sudo pip install -r reqs.txt
```

where `reqs.txt` has

```
funcsigs
futures
tzlocal>=1.2
babelfish>=0.5.5
rebulk>=0.7.0
functools32
MarkupSafe
plumbum
```

After this, flexget is working fine.
I was not yet able to reproduce the problem reported in #9.

2. subliminal fails to execute

As flexget failed to install during `install.sh` execution, subliminal did not install.
I installed it after installing flexget with 

```
sudo pip install subliminal
```

3. `motd`is not updated

The reference to the `motd` script in `install.sh` is incorrect.
It should be (line 98)

```
bash "$INSTALLATION_FOLDER/bash/install_motd.sh"
```

otherwise, you'll get

```
bash: /home/osmc/.raspberry-osmc-automated/bash/motd.sh: No such file or directory
```

during the installation.

4. There is no check for an existing `Downloads` folder

The installation script does not check if the `/home/osmc/Downloads` folder exists.
If it doesn't, flexget will fail on execution with

```
2016-11-05 15:00 CRITICAL manager                       [/tasks/sort-files/filesystem/path] `/home/osmc/Downloads/` does not exist
2016-11-05 15:00 CRITICAL manager                       Failed to load config file: Did not pass schema validation.
```

Perhaps this could be automated?

5. Transmission UI whitelist is not configured

When the installation is done, if you navigate to `http://IP:9091`, you'll get:

```
403: Forbidden

Unauthorized IP Address.

Either disable the IP address whitelist or add your address to it.

If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries.

If you're still using ACLs, use a whitelist instead. See the transmission-daemon manpage for details.
```

This is because `/home/osmc/.config/transmission-daemon/settings.json` is misconfigured.
Lines 50-51 should read (assuming you are on network 192.168.*.*):

```
    "rpc-whitelist": "127.0.0.1,192.168.*.*",
    "rpc-whitelist-enabled": true,
```

Perhaps this could be automated?
In any case, for troubleshooting, here's a reference link: [TransmissionHowTo - Community Help Wiki](https://help.ubuntu.com/community/TransmissionHowTo#Whitelist)

6. `jsonrpc` requests fail

This could be added to troubleshooting.
If you are getting

```
--2016-11-05 15:43:19--  http://localhost/jsonrpc
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:80... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:80... failed: Connection refused.
```

when the `wget` cron entries run, make sure that the web server port is correctly configured as 80 in Kodi. 
Reference link: [Webserver - Official Kodi Wiki](http://kodi.wiki/view/Webserver#Enabling_the_webserver)

7. README enhancements - move installation stuff away, flexget execute

One entry to the `README` file could be something like:

```
Once the installation is done and successful, you can erase the following files:

install.sh
installation.log
```

Also, the command for flexget (line 75) should be:

```
	/usr/local/bin/flexget execute
```

8. Add a mail client to the additional packages list

Since many cron jobs are running, eventually a few mails will appear.
It would be a nice addition to have a mail client (e.g. `mutt`) added to the additional packages.

9. `crontab` improvements

I changed a couple of things in the `crontab`: output suppression and fix of the find command. Here are my changes:

```
--- crontab.original	2016-11-05 20:42:22.617129894 +0000
+++ crontab.final	2016-11-05 20:41:23.117157286 +0000
@@ -1,7 +1,7 @@
-@reboot /usr/local/bin/flexget daemon start -d
+@reboot /usr/local/bin/flexget --loglevel critical daemon start -d
 @hourly /usr/local/bin/flexget --loglevel verbose --cron execute
-@hourly wget --header='Content-Type: application/json' --post-data='{"method": "VideoLibrary.Scan", "id":5,"jsonrpc":"2.0"}' http://localhost/jsonrpc -O /dev/null
-@daily wget --header='Content-Type: application/json' --post-data='{"method": "VideoLibrary.Clean", "id":5,"jsonrpc":"2.0"}' http://localhost/jsonrpc -O /dev/null
+@hourly wget --quiet --header='Content-Type: application/json' --post-data='{"method": "VideoLibrary.Scan", "id":5,"jsonrpc":"2.0"}' http://localhost/jsonrpc -O /dev/null
+@daily wget --quiet --header='Content-Type: application/json' --post-data='{"method": "VideoLibrary.Clean", "id":5,"jsonrpc":"2.0"}' http://localhost/jsonrpc -O /dev/null
 # Delete images, text files and existing subtitles. Then delete any empty dir in Downloads.
-@hourly find /home/osmc/Downloads/. \( -name "*.jpg" -o -name "*.png" -o -name "*.txt" -o -name "*.url" -o -name "*.nfo" -o -name "*.srt" \) -delete && find /home/osmc/Downloads/. -type d -empty -delete
-@hourly /usr/local/bin/subliminal download -l en -s /home/osmc/TV\ Shows/* --age 1w
+@hourly find /home/osmc/Downloads/. \( -name "*.jpg" -o -name "*.png" -o -name "*.txt" -o -name "*.url" -o -name "*.nfo" -o -name "*.srt" \) -delete && find /home/osmc/Downloads/. -mindepth 1 -type d -empty -delete
+@hourly /usr/local/bin/subliminal download -l en -s /home/osmc/TV\ Shows/* --age 1w  > /dev/null
```

Thanks for your work and HTH!

Bernardo

**Comment by alombarte** [comment]
Thank you Bernardo!

This really helps as the code has not been tested for a greater release of 2015.08-1 and when I do it this is going to clear the path, I will certainly use your tests to make ti work with the latest version.

Some comments on each of the steps you mentioned:

1) and 2) For the latest version of OSMC it looks like this dependencies changed all over again. It's very fragile, I have tagged current repository state as working for the release 2015.08-1 and next commits will be towards 2016-*
3) Changed
4) I only tested the script when having external storage. I guess you didn't add external storage so this is why it failed. These folders need to be created because all the rest of the scripts depend on them, so I corrected this in the commit.
5) This is supposed to be done here https://github.com/alombarte/raspberry-osmc-automated/blob/master/bash/install_transmission.sh#L22 I will check later if this fails for any reason. Or it's just maybe than now "rpc-whitelist-enabled": true is also needed because now is false by default.
6) I don't see why should have this error... The crontab precisely uses this addresses. Where this comes from?
7) Definetely
8) The script install_additional_packages.sh adds sendmail (which I use to have the updates in my gmail inbox). If I add mutt, which is a great idea, there should be also some indications/process to have emails running.
9) I've added your suggestions, I also put as critical when flexget runs. This was verbose after the development phase and never changed.

Thank you very much!

**Comment by bernardomaciel** [comment]
Hi again!

Some further comments.
1. 👍
2. 👍
3. 👍
4. You are correct, I did not add external storage.
5. Looking at `~/.raspberry-osmc-automated/bash/settings.cfg` shows that `TRANSMISSION_WHITELIST_RANGE` was set correctly. I don't know what happened :/ Anyway, it seems that your comment on the `rpc-whitelist-enabled` property is correct.
6. I guess I had this problem by enabling/disabling the Kodi webserver and setting it to port 8080. It might be the case for other it port 80 is being used for something else.
7. 👍
8. 👍 
9. Cool! I have two updated suggestions for the crontab
   9.1 I added the redirection below because you can see flexget results in its log and more often then not, I would get an email with `There is a FlexGet process already running for this config, sending execution there.`. Also, the CRITICAL log level is way too high, no?

```
--- crontab.original    2016-11-12 15:29:28.224983974 +0000
+++ crontab.final   2016-11-12 16:30:35.955417196 +0000
@@ -1,5 +1,5 @@
-@reboot /usr/local/bin/flexget --loglevel critical daemon start -d
-@hourly /usr/local/bin/flexget --loglevel critical --cron execute
+@reboot /usr/local/bin/flexget daemon start -d > /dev/null
+@hourly /usr/local/bin/flexget --cron execute > /dev/null
 @hourly wget --quiet --header='Content-Type: application/json' --post-data='{"method": "VideoLibrary.Scan", "id":5,"jsonrpc":"2.0"}' http://localhost/jsonrpc -O /dev/null
 @daily wget --quiet --header='Content-Type: application/json' --post-data='{"method": "VideoLibrary.Clean", "id":5,"jsonrpc":"2.0"}' http://localhost/jsonrpc -O /dev/null
 # Delete images, text files and existing subtitles. Then delete any empty dir in Downloads.
```

9.2 In README.md - Deleting seen shows, you mention: 

> In the crontab there is a commented job that deletes TV shows that are marked as seen by Kodi after 1 month. If you want to enable this feature just uncomment the line in the crontab and save.

I could not find this entry... was it removed?

**Comment by alombarte** [comment]
Thanks,

I added your suggestions to the crontab. Also, it seems that I added the comment mentioning the script to delete shows in the readme but never committed the line. I added a sample in:
https://github.com/alombarte/raspberry-osmc-automated/blob/master/bash/install_crontab.sh#L22

Shouldn't have a fixed path `.raspberry-osmc-automated` but it's commented anyway.

**Comment by bernardomaciel** [comment]
Cool, thanks!
I'll close this as the open items are improvements.

**Comment by alombarte** [comment]
Feel free to open any issues you consider are worth it, even if they are improvements. Or even better do a pull request ;)

Thank you very much for your deep analysis.

**Comment by wagner4362** [comment]
@bernardomaciel Just to explain better in number 5 with we have a issue with transmission daemon ssh server error 403 forbidden I do the below:

sudo chmod 777 -R /home/osmc/.config/transmission-daemon (for me looks like the file dont save after edit just I change the permissions for full read/write access)
sudo service transmission-daemon stop ( stop service beforw edit file)
<edit the file now as you describe>
sudo service transmission-daemon start

Now transmission daemon ssh works for me
