### ISSUE TITLE
Question: OSMC version

### ISSUE THREAD

**Issue by wagner4362** [alombarte/raspberry-osmc-automated#11]
Hi, I'm new here so I'm setting up my first media center in Rpi3 so I ask if is working with latest version of OSMC or I need to downgrade to 2015-08 build of OSMC to work correctly? How proceed about this?

PS: By the way, great project, I'll be grateful if I can help with something.

Thanks.

**Comment by alombarte** [comment]
The latest version has never been tested, but some changes have been made thanks to issue #9 . With this info I believe you can have it running with the latest version.
