### ISSUE TITLE
Add support for uninstallation

### ISSUE THREAD

**Issue by bernardomaciel** [alombarte/raspberry-osmc-automated#15]
It would be great to have support for uninstalling all the components.
It would imply that the `install*.sh` scripts and operations have removal counterparts.
In the end, the system would be restored to its previous state, optionally keeping the already downloaded shows.

**Comment by alombarte** [comment]
I don't really see the value of having this for the cost that is going to have. The main problem I see around this is that all installed (or required) packages installed should be removed, but you don't know if any of the dependencies is still need by the system...

Have you thought in any approach?

**Comment by bernardomaciel** [comment]
Well, one could at least remove the main packages: transmission, subliminal, etc.
I am not an `apt-get` expert but `remove`, `purge` and `autoremove` seem to be the way [(link)](http://askubuntu.com/a/187891).

As for value, I think you have two use cases:

1. Being able to install other stuff from a clean(er) if you decide to use other applications for TV shows
2. Testing

If this is not enough for you, feel free to close this as won't fix. No hard feelings :laughing:

**Comment by alombarte** [comment]
LOL, no hard feelings.

I mark the task as won't fix, at least for now.
