### ISSUE TITLE
Transmiasion remote command not found NEW fix

### ISSUE THREAD

**Issue by wagner4362** [alombarte/raspberry-osmc-automated#18]
Sorry for my mistake, transmission-daemon shows RSS feed as added successfully in terminal but dont works,  for start downloading correctly the RSS content just install transmission-cli than comes with remote function:

sudo apt-get -y install transmission-cli

Now edit /home/osmc/.raspberry-osmc-automated/bash/download_magnets_in_rss.sh line 14 to:
/usr/bin/transmission-remote -a "$magnet"

I checked in my transmission web UI and appears all the magnets added and downloading as planned.

**Comment by alombarte** [comment]
Thanks @wagner4362 . I reviewed my current setup and this is the package I use.

Will fix now
