### ISSUE TITLE
Guardar cambios en setting.json

### ISSUE THREAD

**Issue by ssheduardo** [alombarte/raspberry-osmc-automated#2]
Ante todo gracias por el script que me ha facilitado mucho la instalación de todo el paquete.
Tengo un problema, como puedo modificar setting.json, sin que al reiniciar el demonio se sobreescriba los datos?
Por ejemplo para acceder via web, no puedo dado que están activado estos 2 parámetros:

```
"rpc-whitelist": "127.0.0.1",
"rpc-whitelist-enabled": true,
```

Cambios estoy y otros parámetros y al reiniciar por arte te magia vuelve a estar el fichero como antes.

**Comment by ssheduardo** [comment]
He visto que hay dos ficheros 

```
/etc/transmission-daemon/settings.json 
y
/home/osmc/.config/transmission-daemon/settings.json
```

Cual de los 2 es el que manda para la configuración?

**Comment by alombarte** [comment]
Hola @ssheduardo ,

El script debería haberte hecho la instalación completa, incluida la modificación de esos dos campos. Fíjate en el script que instala transmission que lo primero que hace es parar el daemon:

`sudo /etc/init.d/transmission-daemon stop`

Luego con el daemon parado cambia la configuración (con el comando `sed`) y luego lo vuelve a arrancar. Si tienes el demonio corriendo y modificas la configuración, justo antes de reiniciar lo que hace es guardar la configuración que tenía en memoria en el disco, por lo que se pierde cualquier cambio que hayas hecho. De ahí a que sea necesario modificar con el proceso parado.

Sobre los dos ficheros uno es el del sistema y el otro el del usuario que lo arranca. Yo modifico los dos por que el que manda depende de las condiciones. Pero insisto que eso el script `bash/install_transmission.sh` debería hacer eso por ti. Si el script falla lo miraré, en caso contrario cierro este issue.

Ya me dirás.

Saludos

**Comment by ssheduardo** [comment]
Gracias por la respuesta,
Vale entonces es parar el demonio y ya modificar, pero cual modifico los 2 ficheros?
Si puedes poner en la documentación esto que comentas sería de ayuda, tengo algunas dudas por si ayuda mejorar más el script donde puede hacerlo?
Gracias.

**Comment by alombarte** [comment]
Sí, yo modifico los dos (fíjate en los `sed` del fichero https://github.com/alombarte/raspberry-osmc-automated/blob/master/bash/install_transmission.sh).

La documentación es para instalar todo el proyecto entero, no por partes. Los `.sh` tienen comentarios. ¿Dónde sugieres añadir eso?

Puedes enviar comentarios por email si quieres, mismo usuario que en github y @gmail.com. Si quieres contribuir con código haz un fork y crea un pull request.

Saludos
