### ISSUE TITLE
Switching to Plex  environment

### ISSUE THREAD

**Issue by wagner4362** [alombarte/raspberry-osmc-automated#21]
Maybe this project works on Raspbian with Plex Media Server instead of OSMC? Of course will be needed some tweaks but I didn't like the OSMC and I already used Plex some time ago and its much better in my case, all my devices have the Plex app and the Raspberry don't need to always stay plugged on my TV and working as media server.

I found this [guide](https://www.element14.com/community/community/raspberry-pi/raspberrypi_projects/blog/2016/03/11/a-more-powerful-plex-media-server-using-raspberry-pi-3) about how to setup Plex in Raspberry.

Thanks.

**Comment by alombarte** [comment]
OSMC is the base I used but I think that any other debian based should work too as long as the packages are available for install. This project is nothing else that the configuration of transmission, flexget, subliminal and a few other more tools (which are not OSMC's).

I used Plex years ago and I really liked it, but when I did it there wasn't the ability of downloading the subtitles from the UI. I don't know if this is still true, but it would be very interesting to see it running on Plex if anyone has the time to test it.
