### ISSUE TITLE
Fork and edit the project

### ISSUE THREAD

**Issue by wagner4362** [alombarte/raspberry-osmc-automated#22]
I'm testing this on Raspbian Lite with Plex Media Server and it's needed to change some code lines so, I can fork the project and edit it if I want or can't do that?

**Comment by wagner4362** [comment]
The default home folder for Raspbian (/home/pi) is different from OSMC (/home/osmc)

**Comment by alombarte** [comment]
Sure, you can fork the project and edit there everything you want.

If there are paths hardcoded (/home/osmc) that could easily be dynamic.
