### ISSUE TITLE
Fail the installation as soon as anything goes wrong

### ISSUE THREAD

**Issue by jakzal** [alombarte/raspberry-osmc-automated#27]
At the moment if there's a failure at any point of installation script it just carries on, ignoring the error. I ended up without an incomplete setup (missing flexget).

Adding the following at the top of the installation script would make that it fails if any command fails (-e) or variable is not initialsed (-u). It will also use the exit code of the failing command in a pipeline as a script exit code.

```
set -euo pipefail
```

**Comment by alombarte** [comment]
Thanks @jakzal . I'll add it.

Not sure if there are some errors that should be allowed to carry on, but in any case they should be fixed.

The script was tested long time ago with a previous version. What kind of errors did you get during the install with the newer version of OSMC?

**Comment by jakzal** [comment]
I don't remember what was the error right now, but it was during the flexget installation. I ended up with an environment missing flexget. 

Anyway, anything can go wrong. Even if the script works today, packages which are not under your control might break your stuff tomorrow. Even a simple network interruption might cause installation will end with an inconsistent state.

**Comment by alombarte** [comment]
Totally agree.

Thanks!
