### ISSUE TITLE
Path errors when creating new directories on fresh OSMC install 

### ISSUE THREAD

**Issue by nadelcha** [alombarte/raspberry-osmc-automated#31]
When running script on new OSMC install, pathing errors occur when attempting to mkdir the Downloads/Movies/Music/... files.  Verified when no external storage is being used. 

```Are you storing content on a external storage? If so, what is the mountpoint? (e.g: /media/KINGSTON)
Press ENTER to skip, or write the path now:

Omitting external storage. Preparing folder structure...
mkdir: cannot create directory '/Downloads': Permission denied
mkdir: cannot create directory '/Movies': Permission denied
mkdir: cannot create directory '/Music': Permission denied
mkdir: cannot create directory '/Pictures': Permission denied
mkdir: cannot create directory '/TV Shows': Permission denied 
```

I believe this is due to the fact that when variable $EXTERNAL_STORAGE is left blank, the script attempts to write to the root directory.  See listing below:
```read -r EXTERNAL_STORAGE
if [ "$EXTERNAL_STORAGE" == "" ] || [ ! -d "$EXTERNAL_STORAGE" ] ; then
	echo "Omitting external storage. Preparing folder structure..."
	mkdir -p "$EXTERNAL_STORAGE"/{Downloads/Incomplete,Movies,Music,Pictures,"TV Shows"}
```
A second script halting issue occurs if you try to set the variable to `/home/osmc` since the `else` seems to try linking to the home directory.

**Comment by alombarte** [comment]
Ho @nadelcha ,

You are totally right. I never skipped the external folder. I created a patch directly in the github live editor, so it's untested.

Try with this new branch an see if it works as it should and will merge it to master.

Thank you very much for reporting!
