### ISSUE TITLE
installation stuck in OSMC

### ISSUE THREAD

**Issue by greymda** [alombarte/raspberry-osmc-automated#38]
it goes well for a while, then it stucks on this:

> Searching for flexget
Reading https://pypi.python.org/simple/flexget/

can you point me out to right direction?
cheers

UPDATE: it finally went further but now, when doing this step i get this error:

> osmc@osmc:~/.flexget$ /usr/local/bin/flexget exec
-bash: /usr/local/bin/flexget: No such file or directory

**Comment by alombarte** [comment]
Hi,
I haven't relaunched the process for a while. Probably the path where flexget was installed has changed. Try with `which flexget` or `type flexget` to see if flexget is present and update the script with the new location.

Please provide the versions that you are using in the install.

**Comment by greymda** [comment]
nah, it dont seem to be installed at all.

what versions do you mean?

**Comment by alombarte** [comment]
I meant the OSMC version.

These lines in the script can be problematic:
```
# Dependencies:
sudo apt-get install python-pip python-setuptools --yes
# six>=1.9.0 to run flex needed:
sudo pip install six --upgrade
sudo easy_install flexget
```
It probably got stuck while trying to download it and failed. Try to install flexget again by hand

**Comment by greymda** [comment]
oh my god, it worked! awesome man! thank you!
