### ISSUE TITLE
rmdir: failed to remove ‘/home/osmc/Movies’: Not a directory

### ISSUE THREAD

**Issue by megrimm** [alombarte/raspberry-osmc-automated#4]
should maybe create a check that symbolic exists when running script again?

Deleting default OSMC folders.
rmdir: failed to remove ‘/home/osmc/Movies’: Not a directory
rmdir: failed to remove ‘/home/osmc/Music’: Not a directory
rmdir: failed to remove ‘/home/osmc/Pictures’: Not a directory
rmdir: failed to remove ‘/home/osmc/TV Shows’: Not a directory
Recreating folders but pointing to the external storage
ln: failed to create symbolic link ‘/home/osmc/Downloads’: File exists
ln: failed to create symbolic link ‘/home/osmc/Movies’: File exists
ln: failed to create symbolic link ‘/home/osmc/Music’: File exists
ln: failed to create symbolic link ‘/home/osmc/Pictures’: File exists
ln: failed to create symbolic link ‘/home/osmc/TV Shows’: File exists

**Comment by alombarte** [comment]
The script is thought to bootstrap the machine in a fresh install, not to be run multiple times.

These errors are not a problem since the work is already done, they can be ignored.
