### ISSUE TITLE
line 14: transmission-remote: command not found

### ISSUE THREAD

**Issue by bverc** [alombarte/raspberry-osmc-automated#7]
On the latest version of OSMC, when I try to run the download_magnets_in_rss script, I get the following error:

`/home/osmc/.raspberry-osmc-automated/bash/download_magnets_in_rss.sh: line 14: transmission-remote: command not found`

**Comment by alombarte** [comment]
I have been updating OSMC using the auto-update feature for the past 2? years, si I didn't have the chance to do a fresh install and do an end-to-end testing. I have the latest version of OSMC but the update must respect existing installations and keeps working.

The script assumes that `transmission-remote` is in some folder declared in your $PATH variable. Assuming that transmission-remote is installed try to edit line 14 and put the complete path to the binary. For instance, in my installation that would be:

Line 14: `/usr/bin/transmission-remote -a "$magnet"`

Find out where this transmission-remote is and just add the full path. Let me know where this changed to.

Thanks

**Comment by bverc** [comment]
I've installed transmission-remote-cli, but get the same error. Is transmission-remote different? Where can I find it as is not in package manager.

**Comment by alombarte** [comment]
I believe transmission-remote was part of the installation and I didn't need to install it separately in the past. I think transmission-remote-cli is a different tool.

I've checked my installation and I have installed the packages "transmission-cli" (which I am not sure I use for anything) and "transmission-daemon", and with this I have the binary.

Anyway this script is not used by the raspberry at all, it's only a util for your convenience if you like to play with the command line. You can replace it with transmission-remote-cli or any other tool (even sending a curl request to the transmission interface)

**Comment by wagner4362** [comment]
OSMC 2016 version fix
Replace: transmission-remote -a "$magnet" to transmission-daemon -a "$magnet"

**Comment by alombarte** [comment]
Thanks @wagner4362, I have updated the script.

@bverc can you confirm that works for you?

**Comment by bverc** [comment]
Travelling at the moment, will test when I return. Looks like it will probably do the trick though.

**Comment by alombarte** [comment]
Fixed now in commit for issue #18, thanks to @wagner4362
